"""
Counter-Trend Trading Analyzer
===============================
Identifies weaknesses and contradictions in mainstream economic narratives
and generates trade signals that profit from consensus mispricing.

Philosophy:
- Markets price in consensus narratives — when the narrative diverges from
  underlying fundamentals, a reversion trade opportunity emerges.
- This module detects those divergences, quantifies the mispricing, and
  generates fade / counter-trend signals.

Signal Logic:
  1. Build a Narrative Strength Score for each major macro theme
  2. Compare narrative strength against fundamental reality
  3. Where divergence > threshold → generate counter-trend trade alert
  4. Apply momentum filter to avoid catching falling knives too early
"""

from __future__ import annotations

import copy
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("CounterTrendAnalyzer")


# 
# DATA STRUCTURES
# 


@dataclass
class NarrativeStrength:
    """Encapsulates how strongly the market believes a macro narrative."""

    theme: str  # e.g. "USD Strength", "Fed Hawkishness", "Tech Dominance"
    consensus_score: float  # 0–100 (100 = max consensus belief)
    fundamental_score: float  # 0–100 (100 = fully supported by data)
    divergence: float  # consensus_score − fundamental_score  (+ve = overcrowded)
    narrative_summary: str
    contradictions: List[str] = field(default_factory=list)
    supporting_data: List[str] = field(default_factory=list)


@dataclass
class CounterTrendSignal:
    """A trade signal generated by fading a mispriced narrative."""

    theme: str
    direction: str  # "LONG" or "SHORT"
    asset_class: str  # "FX", "EQUITY", "COMMODITY", "BOND"
    instrument: str  # e.g. "USDJPY=X", "GLD", "TLT"
    signal_strength: float  # 0–100
    confidence: float  # 0–100
    divergence_score: float  # raw narrative divergence
    entry_rationale: str
    macro_narrative: str  # what the crowd believes
    counter_thesis: str  # why the crowd is wrong
    key_risks: List[str]
    catalyst_needed: str  # what would trigger the reversion
    time_horizon: str  # "Days", "Weeks", "Months"
    position_size_pct: float  # suggested % of portfolio
    # Live-price confirmation fields (populated by apply_momentum_filter)
    momentum_state: str = "NO_DATA"  # TREND_ACCELERATING / STALLING / DECELERATING / REVERSING / NO_DATA
    momentum_score: float = 0.0  # −100..+100, +ve = price moving in fade direction
    price_confirmation: str = ""  # human-readable live-price read
    live_price: float = 0.0  # last observed close when price data was supplied
    entry_condition: str = ""  # what to wait for before entering


# 
# NARRATIVE REGISTRY
# 

# Each narrative has:
#   consensus_score   → how universally the market believes it (0–100)
#   fundamental_score → how well the data actually supports it (0–100)
#   theme / summary / contradictions / supporting_data
#
# These are seeded with current macro reality as of early 2026.
# In production, these should be updated from real-time data feeds.

_DEFAULT_NARRATIVES: List[Dict] = [
    {
        "theme": "USD Structural Strength",
        "consensus_score": 72.0,
        "fundamental_score": 48.0,
        "narrative_summary": (
            "The USD is broadly expected to remain strong given US rate "
            "differentials and safe-haven demand."
        ),
        "contradictions": [
            "US twin deficits (fiscal + current account) are at multi-decade highs.",
            "BRICS nations actively reducing USD reserves; de-dollarisation accelerating.",
            "US debt-to-GDP above 120% — fiscal sustainability increasingly questioned.",
            "Fed rate cuts expected to narrow the rate differential advantage.",
            "US manufacturing PMI stuck below 50 for prolonged period.",
        ],
        "supporting_data": [
            "US nominal rates still highest among G10 economies.",
            "USD remains dominant in global trade invoicing (~80%).",
            "Flight-to-quality demand during geopolitical stress favours USD.",
        ],
        "fade_instruments": {
            "FX": ["EURUSD=X", "GBPUSD=X", "AUDUSD=X"],
            "COMMODITY": ["GLD", "SLV"],
        },
        "fade_direction": "LONG",  # Long non-USD = SHORT USD
    },
    {
        "theme": "Fed Hawkishness Permanence",
        "consensus_score": 65.0,
        "fundamental_score": 42.0,
        "narrative_summary": (
            "Market consensus expects the Fed to remain higher-for-longer, "
            "pricing out aggressive rate cuts."
        ),
        "contradictions": [
            "US labour market showing cracks: rising continuing claims, slowing payrolls.",
            "Leading indicators (LEI, ISM) point to economic deceleration.",
            "Commercial real estate stress could force Fed's hand earlier than priced.",
            "Inflation is trending toward 2% target — justification for hawkishness fading.",
            "Historical precedent: Fed almost always cuts faster than dots suggest.",
        ],
        "supporting_data": [
            "Services inflation remains sticky above 4%.",
            "Fed officials maintain hawkish rhetoric in speeches.",
            "Strong jobs headline numbers (though quality deteriorating).",
        ],
        "fade_instruments": {
            "BOND": ["TLT", "IEF", "EDV"],
            "EQUITY": ["XLU", "XLRE"],
        },
        "fade_direction": "LONG",  # Long duration bonds = fade hawkishness narrative
    },
    {
        "theme": "Tech / AI Exceptionalism",
        "consensus_score": 80.0,
        "fundamental_score": 58.0,
        "narrative_summary": (
            "Mega-cap tech and AI names will continue to outperform driven "
            "by structural AI investment supercycle."
        ),
        "contradictions": [
            "AI capex spending not yet reflected in revenue for most beneficiaries.",
            "Concentration risk: top 7 stocks now >30% of S&P 500 — historical extreme.",
            "Valuation multiples at 25–35x EV/FCF for many names — embedded perfection.",
            "Rising competition from open-source and non-US AI (DeepSeek, Mistral).",
            "CapEx cycle may reverse sharply if AI ROI disappoints enterprise buyers.",
        ],
        "supporting_data": [
            "Nvidia revenue growth 200%+ YoY demonstrating real demand.",
            "Hyperscaler capex commitments locked in for 2-3 years.",
            "AI integration beginning to show productivity gains in software.",
        ],
        "fade_instruments": {
            "EQUITY": ["QQQ", "XLK", "NVDA", "SMCI"],
            "ETF": ["SQQQ"],
        },
        "fade_direction": "SHORT",
    },
    {
        "theme": "China Economic Collapse",
        "consensus_score": 70.0,
        "fundamental_score": 45.0,
        "narrative_summary": (
            "Consensus expects prolonged Chinese economic stagnation, "
            "deflation, and property sector collapse with no recovery."
        ),
        "contradictions": [
            "China's manufacturing PMI has been consistently above 50 in 2025.",
            "EV and clean energy exports booming — new growth engine forming.",
            "PBOC has significant dry powder; property stimulus being deployed.",
            "Valuations at historical lows: MSCI China P/E ~9x vs EM average ~13x.",
            "Geopolitical fears pricing in worst-case scenario already.",
        ],
        "supporting_data": [
            "Property sector represents ~25% of GDP — structural drag is real.",
            "Youth unemployment elevated; consumer confidence weak.",
            "Capital outflows pressuring CNY.",
        ],
        "fade_instruments": {
            "EQUITY": ["FXI", "KWEB", "MCHI", "BABA"],
            "FX": ["USDCNH=X"],
        },
        "fade_direction": "LONG",  # Long Chinese equities = fade collapse narrative
    },
    {
        "theme": "Gold is a Relic",
        "consensus_score": 40.0,
        "fundamental_score": 20.0,
        "narrative_summary": (
            "Many institutional investors underweight gold, viewing it as "
            "non-yielding and obsolete in a high-rate environment."
        ),
        "contradictions": [
            "Central bank gold buying at 50-year highs — de-dollarisation demand.",
            "Gold outperforming despite higher real rates — historical relationship broken.",
            "Fiscal dominance risk rising: gold is the only asset with no counterparty risk.",
            "Emerging market central banks increasing gold reserves as USD hedge.",
            "Real rates expected to fall as Fed cuts — structural tailwind for gold.",
        ],
        "supporting_data": [
            "Bitcoin competing for 'store of value' narrative allocation.",
            "High real yields historically negative for non-yielding assets.",
        ],
        "fade_instruments": {
            "COMMODITY": ["GLD", "GDX", "GDXJ", "SLV"],
        },
        "fade_direction": "LONG",
    },
    {
        "theme": "Energy Transition is Linear",
        "consensus_score": 62.0,
        "fundamental_score": 38.0,
        "narrative_summary": (
            "Consensus assumes rapid, smooth transition from fossil fuels "
            "to renewables, leading to structural underinvestment in oil & gas."
        ),
        "contradictions": [
            "Global oil demand still at record highs despite EV adoption.",
            "Energy security concerns post-Ukraine driving fossil fuel investment.",
            "Renewables intermittency problem unsolved — baseload still fossil-fuel dependent.",
            "Oil majors returning capital via buybacks at 10–12% yields — undervalued.",
            "Emerging market oil demand growing faster than EV adoption in DMs.",
        ],
        "supporting_data": [
            "IEA projections call for peak oil demand this decade.",
            "ESG mandates reducing institutional allocation to energy sector.",
        ],
        "fade_instruments": {
            "EQUITY": ["XLE", "XOM", "CVX", "COP"],
            "COMMODITY": ["USO", "UNG"],
        },
        "fade_direction": "LONG",
    },
    {
        "theme": "Small-Cap Permanent Underperformance",
        "consensus_score": 58.0,
        "fundamental_score": 35.0,
        "narrative_summary": (
            "Investors have abandoned small-caps, believing mega-cap dominance "
            "is structural and small caps cannot compete."
        ),
        "contradictions": [
            "Small-cap P/E relative to large-cap at 30-year lows — extreme undervaluation.",
            "Rate cuts disproportionately benefit small-caps (higher floating rate debt).",
            "Reshoring / nearshoring trends favour domestically-focused small companies.",
            "Historically, small-caps significantly outperform in early rate-cut cycles.",
            "Concentration in mega-caps creates fragility — rotation risk is underpriced.",
        ],
        "supporting_data": [
            "Small caps have higher debt burdens — rate sensitivity a genuine risk.",
            "Liquidity premium justifies some discount vs large caps.",
        ],
        "fade_instruments": {
            "EQUITY": ["IWM", "IJR", "VBR"],
            "ETF": ["TNA"],
        },
        "fade_direction": "LONG",
    },
    {
        "theme": "JPY Carry Trade is Safe",
        "consensus_score": 55.0,
        "fundamental_score": 28.0,
        "narrative_summary": (
            "Carry traders remain short JPY, believing BOJ will stay ultra-loose "
            "indefinitely and JPY weakness is structural."
        ),
        "contradictions": [
            "BOJ has already begun hiking — policy normalisation underway.",
            "Japan inflation sustainably above 2% for first time in 30 years.",
            "JPY at multi-decade lows vs USD — extreme valuation by PPP.",
            "Short JPY positioning near historical extremes — crowded trade.",
            "Carry unwinds are violent and fast — August 2024 showed the risk.",
        ],
        "supporting_data": [
            "Rate differential still wide (US 5.25% vs Japan 0.25%).",
            "Carry trade generates positive roll income until BOJ closes gap.",
        ],
        "fade_instruments": {
            "FX": ["USDJPY=X", "EURJPY=X", "GBPJPY=X"],
        },
        "fade_direction": "SHORT",  # Short USDJPY = Long JPY = fade carry consensus
    },
]


# 
# CORE ANALYZER
# 


class CounterTrendAnalyzer:
    """
    Identifies macro narrative contradictions and generates counter-trend
    trade signals where consensus diverges materially from fundamentals.
    """

    # Minimum divergence (consensus − fundamental) to flag a counter-trend opportunity
    DIVERGENCE_THRESHOLD: float = 18.0
    # Minimum signal strength to include in output
    MIN_SIGNAL_STRENGTH: float = 50.0

    def __init__(self, custom_narratives: Optional[List[Dict]] = None):
        self._narratives: List[NarrativeStrength] = []
        # Deep-copy so in-place score refreshes never mutate the shared
        # module-level defaults (which would leak state across instances).
        raw = copy.deepcopy(
            custom_narratives if custom_narratives is not None else _DEFAULT_NARRATIVES
        )
        self._raw_narratives = raw
        self._build_narratives(raw)

    #  Build 

    def _build_narratives(self, raw: List[Dict]) -> None:
        self._narratives = []
        for item in raw:
            cs = float(item.get("consensus_score", 50))
            fs = float(item.get("fundamental_score", 50))
            divergence = cs - fs  # positive = narrative more bullish than data
            self._narratives.append(
                NarrativeStrength(
                    theme=item["theme"],
                    consensus_score=cs,
                    fundamental_score=fs,
                    divergence=divergence,
                    narrative_summary=item.get("narrative_summary", ""),
                    contradictions=item.get("contradictions", []),
                    supporting_data=item.get("supporting_data", []),
                )
            )

    #  Public API 

    def get_all_narratives(self) -> List[NarrativeStrength]:
        """Return all tracked narratives sorted by divergence (most mispriced first)."""
        return sorted(self._narratives, key=lambda n: abs(n.divergence), reverse=True)

    def get_overcrowded_narratives(
        self, threshold: Optional[float] = None
    ) -> List[NarrativeStrength]:
        """Return narratives where consensus significantly outpaces fundamentals."""
        thresh = threshold if threshold is not None else self.DIVERGENCE_THRESHOLD
        return [n for n in self._narratives if n.divergence >= thresh]

    def get_underhyped_narratives(
        self, threshold: Optional[float] = None
    ) -> List[NarrativeStrength]:
        """Return narratives where fundamentals are better than consensus recognises."""
        thresh = threshold if threshold is not None else self.DIVERGENCE_THRESHOLD
        return [n for n in self._narratives if n.divergence <= -thresh]

    def generate_counter_signals(
        self,
        divergence_threshold: Optional[float] = None,
        min_strength: Optional[float] = None,
    ) -> List[CounterTrendSignal]:
        """
        Generate counter-trend trade signals for all materially mispriced narratives.

        Returns a list of signals sorted by signal_strength descending.
        """
        thresh = (
            divergence_threshold
            if divergence_threshold is not None
            else self.DIVERGENCE_THRESHOLD
        )
        min_s = min_strength if min_strength is not None else self.MIN_SIGNAL_STRENGTH

        signals: List[CounterTrendSignal] = []

        for raw_item in self._raw_narratives:
            cs = float(raw_item.get("consensus_score", 50))
            fs = float(raw_item.get("fundamental_score", 50))
            divergence = cs - fs

            if abs(divergence) < thresh:
                continue

            narrative_obj = next(
                (n for n in self._narratives if n.theme == raw_item["theme"]), None
            )
            if narrative_obj is None:
                continue

            fade_instruments: Dict[str, List[str]] = raw_item.get(
                "fade_instruments", {}
            )
            fade_direction: str = raw_item.get("fade_direction", "LONG")

            for asset_class, instruments in fade_instruments.items():
                for instrument in instruments:
                    signal = self._build_signal(
                        narrative=narrative_obj,
                        raw_item=raw_item,
                        asset_class=asset_class,
                        instrument=instrument,
                        fade_direction=fade_direction,
                        divergence=divergence,
                    )
                    if signal.signal_strength >= min_s:
                        signals.append(signal)

        # Sort by signal strength
        signals.sort(key=lambda s: s.signal_strength, reverse=True)
        return signals

    def analyze_instrument(self, instrument: str) -> Optional[CounterTrendSignal]:
        """
        Check if a specific instrument has an active counter-trend signal.
        Returns None if no signal qualifies.
        """
        all_signals = self.generate_counter_signals(
            divergence_threshold=10.0, min_strength=40.0
        )
        inst_upper = instrument.upper().replace("/", "").replace("_", "")
        for sig in all_signals:
            sig_inst = (
                sig.instrument.upper()
                .replace("/", "")
                .replace("_", "")
                .replace("=X", "")
            )
            if sig_inst in inst_upper or inst_upper in sig_inst:
                return sig
        return None

    def apply_momentum_filter(
        self,
        signals: List[CounterTrendSignal],
        price_data: Dict[str, "pd.DataFrame"],
        falling_knife_cutoff: float = 0.03,
    ) -> List[CounterTrendSignal]:
        """Confirm or veto counter-trend signals with live price momentum.

        Fading a narrative is only attractive once the crowd's trend is
        losing momentum — entering while the trend is still accelerating is
        catching a falling knife.  For each signal this:

          1. Computes short (5d) and medium (20d) momentum for the instrument.
          2. Classifies the price action:
               REVERSING        — price already moving in the fade direction
                                  (strongest confirmation, strength boosted)
               DECELERATING     — trend flattening, knife catching
               STALLING         — no trend, range-bound (neutral)
               TREND_ACCELERATING — crowd trend still gaining speed; the
                                  signal is down-weighted and an explicit
                                  entry_condition is attached.
               NO_DATA          — no price series supplied; signal untouched.
          3. Drops signals where the trend is accelerating faster than
             ``falling_knife_cutoff`` per day (default 3%/day, e.g. a
             -15%+ five-day crash) AND momentum is extreme — the classic
             falling-knife case.

        ``price_data`` maps an instrument (e.g. "GLD", "EURUSD=X") to a
        DataFrame with a ``Close`` column (or a plain list of floats).
        """
        if not price_data:
            for s in signals:
                s.momentum_state = "NO_DATA"
                s.price_confirmation = "No live price data supplied - signal is narrative-only."
            return signals

        confirmed: List[CounterTrendSignal] = []
        for sig in signals:
            series = self._extract_close_series(price_data.get(sig.instrument))
            if series is None or len(series) < 21:
                sig.momentum_state = "NO_DATA"
                sig.price_confirmation = "Insufficient price history for momentum confirmation."
                confirmed.append(sig)
                continue

            state, score, read, live_price = self._classify_momentum(series, sig.direction)
            sig.momentum_state = state
            sig.momentum_score = round(score, 1)
            sig.live_price = live_price
            sig.price_confirmation = read

            if state == "TREND_ACCELERATING":
                # Falling knife: penalise hard, never boost.
                sig.signal_strength = round(
                    max(0.0, sig.signal_strength - abs(score) * 0.8), 1
                )
                sig.confidence = round(max(0.0, sig.confidence - 15.0), 1)
                sig.entry_condition = (
                    f"Wait for momentum to stall - do not enter while the trend is still "
                    f"accelerating against the fade (momentum {score:+.0f})."
                )
                # Drop outright when the knife is falling fast enough.
                daily = self._daily_slope(series)
                if daily is not None and abs(daily) >= falling_knife_cutoff:
                    continue
            elif state == "REVERSING":
                sig.signal_strength = round(min(100.0, sig.signal_strength + 8.0), 1)
                sig.confidence = round(min(95.0, sig.confidence + 8.0), 1)
                sig.entry_condition = "Price already moving in the fade direction - valid entry zone."
            elif state == "DECELERATING":
                sig.signal_strength = round(min(100.0, sig.signal_strength + 4.0), 1)
                sig.entry_condition = "Momentum flattening - knife catching; scale in on stabilisation."
            else:  # STALLING
                sig.entry_condition = "Range-bound - fade only on a confirmed break of the range."

            confirmed.append(sig)

        confirmed.sort(key=lambda s: s.signal_strength, reverse=True)
        return confirmed

    @staticmethod
    def _extract_close_series(data: Optional[Any]) -> Optional[List[float]]:
        """Pull a list of closes from a DataFrame, a Series, or a plain list."""
        if data is None:
            return None
        try:
            if hasattr(data, "columns") and "Close" in data.columns:
                vals = [float(x) for x in data["Close"].dropna().tolist()]
            elif hasattr(data, "tolist"):
                vals = [float(x) for x in data.dropna().tolist()]
            else:
                vals = [float(x) for x in data]
        except Exception:
            return None
        return vals if vals else None

    @staticmethod
    def _daily_slope(series: List[float]) -> Optional[float]:
        """Average daily % change over the last 5 sessions."""
        if len(series) < 6:
            return None
        recent = series[-6:]
        try:
            return (recent[-1] - recent[0]) / recent[0] / 5.0
        except Exception:
            return None

    @classmethod
    def _classify_momentum(
        cls, series: List[float], direction: str
    ) -> Tuple[str, float, str, float]:
        """Classify price momentum relative to a fade direction.

        Returns (state, score, human_readable, last_price).  Score is on
        −100..+100 where positive means price is moving WITH the fade
        (i.e. confirming the counter-trend trade).
        """
        last = series[-1]
        ret_5 = (last / series[-6] - 1.0) * 100.0 if len(series) >= 6 else 0.0
        ret_20 = (last / series[-21] - 1.0) * 100.0 if len(series) >= 21 else 0.0

        # For a LONG fade we want price rising; for SHORT we want it falling.
        sign = 1.0 if direction == "LONG" else -1.0
        mom_5 = ret_5 * sign
        mom_20 = ret_20 * sign

        # Score: blend short+medium momentum in the fade direction (−100..+100)
        score = max(-100.0, min(100.0, mom_5 * 2.0 + mom_20 * 1.5))

        if mom_5 > 0 and mom_20 > 0:
            state = "REVERSING"
        elif mom_5 > 0 and mom_20 <= 0:
            state = "DECELERATING"
        elif mom_5 <= 0 and mom_20 <= 0 and score < -15:
            state = "TREND_ACCELERATING"
        else:
            state = "STALLING"

        read = (
            f"Last close {last:.4f}; 5d {ret_5:+.2f}%, 20d {ret_20:+.2f}%. "
            f"Momentum state: {state}."
        )
        return state, score, read, last

    def refresh_from_market_data(
        self, market_data: Dict[str, float], in_place: bool = True
    ) -> List[str]:
        """Adjust narrative consensus/fundamental scores from live market data.

        Replaces the static seeded scores with data-conditioned ones wherever
        a matching observation is provided.  ``market_data`` accepts any of:

          vix                 : current VIX level
          us_10y_yield        : 10Y US Treasury yield (%)
          usd_index           : DXY level
          gold_price          : spot gold price (e.g. 2400)
          usdjpy              : USD/JPY rate
          oil_price           : WTI price
          sp500               : S&P 500 level
          smh_price           : semiconductor ETF price

        Returns the list of themes whose scores were updated.
        """
        updated: List[str] = []

        def _adj(theme: str, consensus_delta: float = 0.0, fundamental_delta: float = 0.0):
            for item in self._raw_narratives:
                if item.get("theme") != theme:
                    continue
                item["consensus_score"] = max(
                    5.0, min(95.0, float(item.get("consensus_score", 50)) + consensus_delta)
                )
                item["fundamental_score"] = max(
                    5.0, min(95.0, float(item.get("fundamental_score", 50)) + fundamental_delta)
                )
                updated.append(theme)
                return

        vix = market_data.get("vix")
        yield_10y = market_data.get("us_10y_yield")
        dxy = market_data.get("usd_index")
        gold = market_data.get("gold_price")
        usdjpy = market_data.get("usdjpy")
        oil = market_data.get("oil_price")
        smh = market_data.get("smh_price")

        # USD strength: high/rising DXY supports the consensus, deficits aside.
        if dxy:
            _adj("USD Structural Strength", consensus_delta=(dxy - 100.0) * 0.3)
        if vix:
            # Risk-off (high VIX) weakens the higher-for-longer / USD-bull case
            _adj("USD Structural Strength", consensus_delta=-(vix - 15.0) * 0.5)
            _adj("Fed Hawkishness Permanence", consensus_delta=-(vix - 15.0) * 0.8)
            _adj("Tech / AI Exceptionalism", consensus_delta=-(vix - 15.0) * 0.9)
            # Small caps get hit hardest in stress: fundamental case strengthens
            _adj("Small-Cap Permanent Underperformance", fundamental_delta=(vix - 15.0) * 0.5)
        if yield_10y:
            # Falling yields undermine the hawkish-permanence narrative
            _adj("Fed Hawkishness Permanence", consensus_delta=(yield_10y - 4.2) * -6.0)
            _adj("Fed Hawkishness Permanence", fundamental_delta=(yield_10y - 4.2) * 3.0)
        if gold:
            # Rising gold erodes the "relic" belief and supports fundamentals
            _adj("Gold is a Relic", consensus_delta=(gold - 2300.0) * -0.02)
            _adj("Gold is a Relic", fundamental_delta=(gold - 2300.0) * 0.03)
        if usdjpy:
            # Higher USD/JPY = more carry complacency = consensus stronger
            _adj("JPY Carry Trade is Safe", consensus_delta=(usdjpy - 150.0) * 0.8)
            # BOJ normalisation risk grows as the pair stretches
            _adj("JPY Carry Trade is Safe", fundamental_delta=(usdjpy - 150.0) * -0.4)
        if oil:
            _adj("Energy Transition is Linear", fundamental_delta=(oil - 75.0) * 0.4)
        if smh:
            _adj("Tech / AI Exceptionalism", consensus_delta=(smh - 250.0) * 0.05)

        self._build_narratives(self._raw_narratives)
        return updated

    def get_narrative_report(self) -> str:
        """
        Generate a human-readable narrative report summarising key contradictions
        and counter-trend opportunities.
        """
        lines = [
            "=" * 70,
            "COUNTER-TREND MACRO NARRATIVE REPORT",
            "=" * 70,
            "",
            "MOST MISPRICED NARRATIVES (Consensus vs Fundamentals):",
            "-" * 60,
        ]

        for n in self.get_all_narratives()[:5]:
            direction = "OVERCROWDED" if n.divergence > 0 else "UNDERPRICED"
            lines.append(f"\n[{direction}] {n.theme}")
            lines.append(f"  Consensus Score : {n.consensus_score:.0f}/100")
            lines.append(f"  Fundamental Score: {n.fundamental_score:.0f}/100")
            lines.append(f"  Divergence       : {n.divergence:+.0f} pts")
            lines.append(f"  Summary: {n.narrative_summary}")
            if n.contradictions:
                lines.append("  Key Contradictions:")
                for c in n.contradictions[:3]:
                    lines.append(f"    • {c}")

        lines += [
            "",
            "=" * 70,
            "ACTIVE COUNTER-TREND SIGNALS:",
            "-" * 60,
        ]

        signals = self.generate_counter_signals()
        seen_themes = set()
        for sig in signals:
            if sig.theme in seen_themes:
                continue
            seen_themes.add(sig.theme)
            lines.append(
                f"\n{sig.direction} {sig.instrument} | Strength: {sig.signal_strength:.0f}/100"
            )
            lines.append(f"  Theme: {sig.theme}")
            lines.append(f"  Counter-Thesis: {sig.counter_thesis}")
            lines.append(f"  Catalyst Needed: {sig.catalyst_needed}")

        return "\n".join(lines)

    #  Internal Signal Builder 

    def _build_signal(
        self,
        narrative: NarrativeStrength,
        raw_item: Dict,
        asset_class: str,
        instrument: str,
        fade_direction: str,
        divergence: float,
    ) -> CounterTrendSignal:
        """Construct a CounterTrendSignal from a narrative and instrument."""

        # Signal strength: scaled from divergence magnitude (0–100)
        # 20 pt divergence → 50 signal strength; 40 pt → 80; 50 pt → 100
        raw_strength = min(100.0, 30.0 + abs(divergence) * 1.75)

        # Confidence: higher when contradictions are numerous and specific
        contradiction_count = len(narrative.contradictions)
        confidence = min(95.0, 40.0 + contradiction_count * 8.0)

        # Position size: proportional to signal strength, capped at 8%
        position_size = round(min(8.0, raw_strength * 0.07), 1)

        # Time horizon based on divergence magnitude
        if abs(divergence) >= 40:
            time_horizon = "Weeks–Months"
        elif abs(divergence) >= 25:
            time_horizon = "Weeks"
        else:
            time_horizon = "Days–Weeks"

        # Entry rationale
        side_word = "long" if fade_direction == "LONG" else "short"
        entry_rationale = (
            f"Go {side_word} {instrument} to fade the '{narrative.theme}' narrative. "
            f"Consensus score ({narrative.consensus_score:.0f}) exceeds fundamental "
            f"support ({narrative.fundamental_score:.0f}) by {abs(divergence):.0f} pts — "
            f"classic mispricing signal. "
            f"{contradiction_count} data-driven contradictions identified."
        )

        # Counter-thesis: synthesise top contradiction
        top_contradiction = (
            narrative.contradictions[0]
            if narrative.contradictions
            else "Narrative not supported by data."
        )
        counter_thesis = (
            f"The '{narrative.theme}' narrative is overcrowded and priced to perfection. "
            f"Key flaw: {top_contradiction}"
        )

        # Catalyst for reversion
        catalyst = self._infer_catalyst(narrative.theme, raw_item)

        # Key risks
        key_risks = [
            f"Narrative could persist longer than expected — timing risk.",
            f"Requires catalyst to unlock reversion — patience needed.",
        ]
        if narrative.supporting_data:
            key_risks.append(
                f"Narrative has genuine support: {narrative.supporting_data[0]}"
            )

        return CounterTrendSignal(
            theme=narrative.theme,
            direction=fade_direction,
            asset_class=asset_class,
            instrument=instrument,
            signal_strength=round(raw_strength, 1),
            confidence=round(confidence, 1),
            divergence_score=round(divergence, 1),
            entry_rationale=entry_rationale,
            macro_narrative=narrative.narrative_summary,
            counter_thesis=counter_thesis,
            key_risks=key_risks,
            catalyst_needed=catalyst,
            time_horizon=time_horizon,
            position_size_pct=position_size,
        )

    @staticmethod
    def _infer_catalyst(theme: str, raw_item: Dict) -> str:
        """Infer what catalyst would trigger narrative reversion."""
        catalysts = {
            "USD Structural Strength": (
                "Fed rate cut cycle acceleration or US fiscal/credit downgrade event."
            ),
            "Fed Hawkishness Permanence": (
                "Weaker-than-expected NFP, rising unemployment rate, or CPI surprise to the downside."
            ),
            "Tech / AI Exceptionalism": (
                "AI revenue disappointment in earnings, margin compression, or regulatory action."
            ),
            "China Economic Collapse": (
                "PBOC / MOFCOM fiscal bazooka stimulus announcement or property floor data."
            ),
            "Gold is a Relic": (
                "Central bank reserve announcement, real rate decline, or fiscal risk event."
            ),
            "Energy Transition is Linear": (
                "Supply shock, geopolitical event, or energy security policy reversal."
            ),
            "Small-Cap Permanent Underperformance": (
                "First Fed rate cut or rotation signal from institutional allocators."
            ),
            "JPY Carry Trade is Safe": (
                "BOJ rate hike surprise, Japan CPI upside, or risk-off event triggering carry unwind."
            ),
        }
        return catalysts.get(
            theme, "Data releases contradicting the consensus narrative."
        )


# 
# NARRATIVE SCORING UTILITIES
# 


def score_narrative_strength(
    consensus_score: float,
    fundamental_score: float,
    sentiment_score: float = 50.0,
    positioning_score: float = 50.0,
) -> Dict:
    """
    Composite scoring that blends market sentiment and positioning data
    into the narrative divergence calculation.

    Parameters
    ----------
    consensus_score     : 0–100, how strongly market believes the narrative
    fundamental_score   : 0–100, how well data actually supports it
    sentiment_score     : 0–100, news/social sentiment alignment (50=neutral)
    positioning_score   : 0–100, COT/fund flow crowdedness (100=max long crowding)

    Returns
    -------
    dict with composite_divergence, fade_conviction, interpretation
    """
    # Narrative divergence (consensus vs fundamentals)
    narrative_div = consensus_score - fundamental_score

    # Positioning component: add extra weight if positioning is also crowded
    positioning_boost = (positioning_score - 50.0) * 0.4  # -20 to +20

    # Sentiment component: one-directional sentiment adds to overcrowding
    sentiment_boost = (sentiment_score - 50.0) * 0.2  # -10 to +10

    composite_divergence = narrative_div + positioning_boost + sentiment_boost

    # Fade conviction
    if abs(composite_divergence) >= 35:
        conviction = "STRONG"
    elif abs(composite_divergence) >= 20:
        conviction = "MODERATE"
    elif abs(composite_divergence) >= 10:
        conviction = "WEAK"
    else:
        conviction = "NONE"

    if composite_divergence > 0:
        interpretation = (
            f"Narrative OVERCROWDED by {composite_divergence:+.1f} pts — fade potential"
        )
    elif composite_divergence < -10:
        interpretation = f"Narrative UNDERHYPED by {abs(composite_divergence):.1f} pts — contrarian long"
    else:
        interpretation = "Narrative fairly priced — no counter-trend signal"

    return {
        "narrative_divergence": round(narrative_div, 1),
        "positioning_boost": round(positioning_boost, 1),
        "sentiment_boost": round(sentiment_boost, 1),
        "composite_divergence": round(composite_divergence, 1),
        "fade_conviction": conviction,
        "interpretation": interpretation,
        "fade_direction": "SHORT" if composite_divergence > 0 else "LONG",
    }


def identify_macro_contradictions(
    economic_indicators: Dict[str, float],
    market_prices: Dict[str, float],
) -> List[str]:
    """
    Cross-reference economic indicator data against market price levels
    to surface objective contradictions.

    Parameters
    ----------
    economic_indicators : dict mapping indicator name → value
        e.g. {"us_10y_yield": 4.25, "us_cpi_yoy": 3.1, "ism_manufacturing": 47.2}
    market_prices : dict mapping asset → price
        e.g. {"SPX": 5000, "USDJPY": 155, "GLD": 2400}

    Returns
    -------
    List of contradiction strings ready for display.
    """
    contradictions = []

    # USD vs Deficits
    usdjpy = market_prices.get("USDJPY", 0)
    us_current_account = economic_indicators.get("us_current_account_pct_gdp", 0)
    if usdjpy > 145 and us_current_account < -3.0:
        contradictions.append(
            f"USD/JPY at {usdjpy:.0f} despite US current account deficit of "
            f"{us_current_account:.1f}% GDP — historically unsustainable."
        )

    # Equities vs PMI
    spx = market_prices.get("SPX", 0)
    ism_mfg = economic_indicators.get("ism_manufacturing", 50)
    if spx > 4800 and ism_mfg < 48:
        contradictions.append(
            f"S&P 500 above 4800 while ISM Manufacturing at {ism_mfg:.1f} "
            f"(contraction territory) — growth premium looks stretched."
        )

    # Bonds vs Inflation
    yield_10y = economic_indicators.get("us_10y_yield", 0)
    cpi_yoy = economic_indicators.get("us_cpi_yoy", 0)
    real_rate = yield_10y - cpi_yoy
    if real_rate > 2.0:
        contradictions.append(
            f"Real 10Y yield at {real_rate:.1f}% — historically restrictive level "
            f"inconsistent with equity valuations above 20x P/E."
        )

    # Gold vs Real Rates
    gold = market_prices.get("GLD", 0)
    if gold > 200 and real_rate > 1.5:
        contradictions.append(
            f"Gold (GLD ${gold:.0f}) rising despite real rates at {real_rate:.1f}% "
            f"— traditional inverse relationship breaking down, suggesting structural demand shift."
        )

    # Credit spreads vs equity vol
    vix = economic_indicators.get("vix", 0)
    hy_spread = economic_indicators.get("hy_spread_bps", 0)
    if vix < 15 and hy_spread > 400:
        contradictions.append(
            f"VIX at {vix:.0f} (complacency) while HY credit spreads at {hy_spread:.0f}bps "
            f"— equity and credit markets pricing very different risks."
        )

    return contradictions


# 
# SINGLETON
# 

_analyzer_instance: Optional[CounterTrendAnalyzer] = None


def get_counter_trend_analyzer() -> CounterTrendAnalyzer:
    """Return the global CounterTrendAnalyzer singleton."""
    global _analyzer_instance
    if _analyzer_instance is None:
        _analyzer_instance = CounterTrendAnalyzer()
    return _analyzer_instance
