"""
Terms of Service & Legal Policy - Octavian Terminal
Bulletproof legal shield removing all liability for financial advice,
simulated trading, and investment losses.
"""

import streamlit as st
from datetime import datetime

try:
    from octavian_theme import COLORS
except ImportError:
    COLORS = {"navy": "#0a1628", "gold": "#c9a84c", "text_primary": "#e8eaf0", "border": "#1e3050"}


def render_terms_of_service():
    st.markdown(f"""
    <div style="max-width:900px;margin:0 auto;padding:30px;">
        <h1 style="color:{COLORS['gold']};text-align:center;letter-spacing:3px;">OCTAVIAN TERMINAL</h1>
        <h2 style="color:{COLORS['text_primary']};text-align:center;">Terms of Service & Legal Disclaimer</h2>
        <p style="color:#999;text-align:center;">Last Updated: {datetime.now().strftime('%B %d, %Y')}</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")

    st.markdown("""
## 1. ACCEPTANCE OF TERMS

By accessing, using, or interacting with the Octavian Terminal platform ("Platform"), you ("User") agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you must immediately cease all use of the Platform.

## 2. NATURE OF THE PLATFORM

**Octavian Terminal is an educational and research tool ONLY.** The Platform provides:
- Market data visualization and analytics
- Simulated (paper) trading environments
- Algorithmic strategy backtesting
- Machine learning-based pattern recognition
- Financial document analysis
- Commodities, options, futures, and FX research tools

**THE PLATFORM DOES NOT PROVIDE:**
- Licensed financial advice
- Investment recommendations
- Tax advice
- Legal counsel
- Guaranteed returns or outcomes

## 3. NO INVESTMENT ADVICE DISCLAIMER

**CRITICAL: NOTHING ON THIS PLATFORM CONSTITUTES INVESTMENT ADVICE.**

All analysis, signals, predictions, scores, trade setups, recommendations, and AI-generated content are provided for **informational and educational purposes only**. They do not constitute a solicitation, recommendation, endorsement, or offer to buy, sell, or hold any security, financial product, or instrument.

The Platform's outputs -- including but not limited to "Breaking Trades," "Institutional Strategy Outlook," ML model predictions, position optimization suggestions, and portfolio analysis -- are **algorithmic outputs based on historical data** and should NOT be interpreted as professional financial advice.

## 4. ASSUMPTION OF RISK

You expressly acknowledge and agree that:

- **All trading and investing involves substantial risk of loss**, including the potential loss of your entire investment.
- **Past performance is not indicative of future results.** Historical backtesting data does not guarantee future performance.
- **Simulated trading results have inherent limitations.** Paper trading does not involve real financial risk and may not accurately reflect actual market conditions including slippage, liquidity, and execution delays.
- **Machine learning models are probabilistic, not deterministic.** Any prediction, forecast, or signal generated by the Platform's AI/ML systems carries uncertainty and may be incorrect.
- **Options, futures, commodities, and derivatives carry heightened risk** including leverage risk, margin calls, and the potential for losses exceeding the initial investment.
- You are solely responsible for your own investment decisions and due diligence.

## 5. LIMITATION OF LIABILITY

**TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:**

The Platform, its creators, developers, operators, affiliates, and contributors ("Platform Parties") shall NOT be liable for:

- Any direct, indirect, incidental, special, consequential, or punitive damages
- Loss of profits, revenue, data, or business opportunities
- Financial losses arising from reliance on Platform outputs
- Trading losses, margin calls, or account liquidations
- Errors, inaccuracies, or omissions in data, analysis, or predictions
- System downtime, data feed interruptions, or technical failures
- Third-party data provider errors or delays
- Any decision made based on Platform content

**THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND**, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement.

## 6. INDEMNIFICATION

You agree to indemnify, defend, and hold harmless the Platform Parties from any claims, liabilities, damages, losses, costs, or expenses (including reasonable legal fees) arising from:
- Your use or misuse of the Platform
- Your trading or investment activities
- Your violation of these Terms
- Any third-party claims related to your use of the Platform

## 7. DATA & PRIVACY

- The Platform may store user preferences, watchlists, and paper trading data locally.
- No personally identifiable information is transmitted to external servers unless explicitly stated.
- Market data is sourced from third-party providers (Yahoo Finance, OANDA, etc.) and is subject to their respective terms.
- The Platform does not sell, share, or distribute user data.

## 8. INTELLECTUAL PROPERTY

All code, algorithms, models, analytics frameworks, UI designs, and branding within the Octavian Terminal are proprietary. Unauthorized reproduction, distribution, or reverse engineering is prohibited.

## 9. REGULATORY COMPLIANCE

- The Platform is **not registered** with the SEC, FINRA, CFTC, NFA, or any other regulatory body as a broker-dealer, investment adviser, or commodity trading adviser.
- Users are responsible for ensuring their activities comply with all applicable local, state, federal, and international laws and regulations.
- The Platform does not execute real trades or manage real money.

## 10. MODIFICATION OF TERMS

The Platform reserves the right to modify these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the modified Terms.

## 11. GOVERNING LAW

These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles.

## 12. SEVERABILITY

If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.

---

**BY USING THE OCTAVIAN TERMINAL, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.**
    """)

    st.markdown("---")

    # Acknowledgment section
    ack_key = "tos_acknowledged"
    if not st.session_state.get(ack_key):
        st.warning("You must acknowledge the Terms of Service to continue using the platform.")
        if st.button("I Have Read and Accept the Terms of Service", type="primary", key="tos_accept_btn"):
            st.session_state[ack_key] = True
            st.success("Terms of Service acknowledged. Thank you.")
            st.rerun()
    else:
        st.success("Terms of Service acknowledged.")
